### PR TITLE
Specify min version for unf_ext

### PR DESCRIPTION
**Pull request by CAMOBAP795**
@ronaldtse @andrew2net should we remove the restriction at all?

### CODE REVIEW

**Comment by andrew2net** [comment]
@CAMOBAP795 I think it would be better if the restriction will remain.

**Comment by ronaldtse** [comment]
I think this makes sense. @andrew2net if it's OK with you can you merge? Thanks.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by ronaldtse** [comment]
Will we get a new release soon?

**Pull request merged**
